name: Rust

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --check
    - name: clippy
      if: always()
      run: cargo clippy

  rust-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Check
      run: cargo check
    - name: Run tests
      run: cargo test -r --verbose
