name: Rust

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - run: cargo fmt --check
    - if: always()
      run: cargo clippy

  rust-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        persist-credentials: false
    - run: cargo check
    - run: cargo test -r --verbose

  rust-latest-deps:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        persist-credentials: false
    - run: cargo update --verbose
    - run: cargo test -r --verbose
